import dataclasses
import logging
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, cast

import yaml

_logger = logging.getLogger(__name__)

MANIFEST_VERSION = 3
MANIFEST_HEADER = "# GENERATED by CAR - DO NOT EDIT\n"
_SAFE_REPO_ID_PATTERN = re.compile(r"^[A-Za-z0-9._-]+$")
_SANITIZE_REPO_ID_PATTERN = re.compile(r"[^A-Za-z0-9._-]+")


def is_safe_repo_id(value: str) -> bool:
    return bool(value and _SAFE_REPO_ID_PATTERN.match(value))


def sanitize_repo_id(value: str) -> str:
    base = (value or "").strip()
    base = _SANITIZE_REPO_ID_PATTERN.sub("-", base)
    base = base.strip("-")
    return base or "repo"


def ensure_unique_repo_id(base: str, existing_ids: set[str]) -> str:
    if base not in existing_ids:
        return base
    suffix = 2
    candidate = f"{base}-{suffix}"
    while candidate in existing_ids:
        suffix += 1
        candidate = f"{base}-{suffix}"
    return candidate


class ManifestError(Exception):
    pass


@dataclasses.dataclass(frozen=True)
class ManifestValidationIssue:
    repo_id: str
    message: str


def preserve_manifest_destination(value: Any) -> Optional[Dict[str, Any]]:
    """Keep destination payload mappings round-trippable, including invalid values."""
    if not isinstance(value, dict):
        return None
    preserved: Dict[str, Any] = {}
    for raw_key, raw_value in value.items():
        if not isinstance(raw_key, str):
            continue
        key = raw_key.strip()
        if not key:
            continue
        if key == "kind" and isinstance(raw_value, str):
            preserved[key] = raw_value.strip()
            continue
        preserved[key] = raw_value
    return preserved


def normalize_manifest_destination(value: Any) -> Optional[Dict[str, Any]]:
    """Normalize destination payloads; return None for invalid shapes."""
    normalized = preserve_manifest_destination(value)
    if normalized is None:
        return None
    kind = normalized.get("kind")
    if not isinstance(kind, str) or not kind.strip():
        return None
    normalized["kind"] = kind.strip()
    return normalized


@dataclasses.dataclass
class ManifestRepo:
    id: str
    path: Path  # relative to hub root
    enabled: bool = True
    auto_run: bool = False
    kind: str = "base"  # base|worktree
    worktree_of: Optional[str] = None
    branch: Optional[str] = None
    display_name: Optional[str] = None
    worktree_setup_commands: Optional[List[str]] = None
    destination: Optional[Dict[str, Any]] = None

    def to_dict(self, hub_root: Path) -> Dict[str, object]:
        rel = _relative_to_hub_root(hub_root, self.path)
        payload: Dict[str, object] = {
            "id": self.id,
            "path": rel.as_posix(),
            "enabled": bool(self.enabled),
            "auto_run": bool(self.auto_run),
            "kind": str(self.kind),
        }
        if self.display_name:
            payload["display_name"] = str(self.display_name)
        if self.worktree_of:
            payload["worktree_of"] = str(self.worktree_of)
        if self.branch:
            payload["branch"] = str(self.branch)
        if self.worktree_setup_commands:
            payload["worktree_setup_commands"] = [
                str(cmd) for cmd in self.worktree_setup_commands if str(cmd).strip()
            ]
        destination = preserve_manifest_destination(self.destination)
        if destination is not None:
            payload["destination"] = destination
        return payload


@dataclasses.dataclass
class Manifest:
    version: int
    repos: List[ManifestRepo]
    issues: List[ManifestValidationIssue] = dataclasses.field(
        default_factory=list,
        repr=False,
        compare=False,
    )

    def get(self, repo_id: str) -> Optional[ManifestRepo]:
        for repo in self.repos:
            if repo.id == repo_id:
                return repo
        return None

    def get_by_path(self, hub_root: Path, repo_path: Path) -> Optional[ManifestRepo]:
        normalized_path = _relative_to_hub_root(hub_root, repo_path)
        for repo in self.repos:
            if repo.path == normalized_path:
                return repo
        return None

    def issues_for_repo(self, repo_id: str) -> List[str]:
        return [
            issue.message
            for issue in self.issues
            if issue.repo_id in {repo_id, "manifest"}
        ]

    def ensure_repo(
        self,
        hub_root: Path,
        repo_path: Path,
        repo_id: Optional[str] = None,
        display_name: Optional[str] = None,
        *,
        kind: str = "base",
        worktree_of: Optional[str] = None,
        branch: Optional[str] = None,
        worktree_setup_commands: Optional[List[str]] = None,
        destination: Optional[Dict[str, Any]] = None,
    ) -> ManifestRepo:
        base_name = display_name or repo_id or repo_path.name
        repo_id = sanitize_repo_id(repo_id or base_name)
        existing = self.get(repo_id)
        if existing:
            if display_name and not existing.display_name:
                existing.display_name = display_name
            return existing
        existing_ids = {repo.id for repo in self.repos}
        repo_id = ensure_unique_repo_id(repo_id, existing_ids)
        normalized_path = _relative_to_hub_root(hub_root, repo_path)
        repo = ManifestRepo(
            id=repo_id,
            path=normalized_path,
            enabled=True,
            auto_run=False,
            kind=str(kind),
            worktree_of=str(worktree_of) if worktree_of else None,
            branch=str(branch) if branch else None,
            display_name=display_name or base_name,
            worktree_setup_commands=(
                [str(cmd) for cmd in worktree_setup_commands if str(cmd).strip()]
                if worktree_setup_commands
                else None
            ),
            destination=normalize_manifest_destination(destination),
        )
        self.repos.append(repo)
        return repo


def match_base_repo_id(
    manifest: Manifest,
    hub_root: Path,
    base_name: str,
    *,
    base_path: Optional[Path],
) -> str:
    normalized_base = sanitize_repo_id(base_name)
    if base_path is not None:
        existing = manifest.get_by_path(hub_root, base_path)
        if existing is not None:
            return existing.id
    for repo in manifest.repos:
        if repo.kind != "base":
            continue
        display_name = (repo.display_name or "").strip()
        if display_name == base_name or repo.id == normalized_base:
            return repo.id
    return normalized_base


def _strip_deprecated_manifest_top_keys(data: Dict[str, Any]) -> List[str]:
    """Drop removed manifest sections; return human-readable keys removed (for logs)."""
    removed: List[str] = []
    _legacy_ws_section = "agent_" + "workspaces"
    if _legacy_ws_section in data:
        del data[_legacy_ws_section]
        removed.append(_legacy_ws_section)
    agents_block = data.get("agents")
    _legacy_agent_runtime = "".join(("zero", "claw"))
    if isinstance(agents_block, dict) and _legacy_agent_runtime in agents_block:
        del agents_block[_legacy_agent_runtime]
        removed.append(f"agents.{_legacy_agent_runtime}")
        if not agents_block:
            del data["agents"]
    return removed


def _relative_to_hub_root(hub_root: Path, target: Path) -> Path:
    if not target.is_absolute():
        target = (hub_root / target).resolve()
    else:
        target = target.resolve()
    try:
        return target.relative_to(hub_root)
    except ValueError:
        return Path(os.path.relpath(target, hub_root))


def _parse_manifest_repos_with_issues(
    *,
    repos_data: Any,
    hub_root: Path,
) -> tuple[List[ManifestRepo], List[ManifestValidationIssue]]:
    if repos_data is None:
        return [], []

    issues: List[ManifestValidationIssue] = []
    if not isinstance(repos_data, list):
        issues.append(
            ManifestValidationIssue(
                repo_id="manifest",
                message="manifest 'repos' must be a list",
            )
        )
        return [], issues

    # Import lazily to avoid circular-import issues at module import time.
    from .core.destinations import parse_destination_config

    repos: List[ManifestRepo] = []
    for idx, entry in enumerate(repos_data):
        if not isinstance(entry, dict):
            issues.append(
                ManifestValidationIssue(
                    repo_id=f"<index:{idx}>",
                    message="repo entry must be an object",
                )
            )
            continue

        repo_id = entry.get("id")
        path_val = entry.get("path")
        repo_label = (
            repo_id.strip()
            if isinstance(repo_id, str) and repo_id.strip()
            else f"<index:{idx}>"
        )
        if not isinstance(repo_id, str) or not repo_id.strip():
            issues.append(
                ManifestValidationIssue(
                    repo_id=repo_label,
                    message="repo entry requires non-empty string 'id'",
                )
            )
            continue
        if not isinstance(path_val, str) or not path_val.strip():
            issues.append(
                ManifestValidationIssue(
                    repo_id=repo_label,
                    message=f"repo '{repo_id}' requires non-empty string 'path'",
                )
            )
            continue
        kind = entry.get("kind")
        if kind not in ("base", "worktree"):
            raise ManifestError(
                f"Invalid manifest repo kind for {repo_id}: {kind} (expected base|worktree)"
            )

        destination = (
            preserve_manifest_destination(entry.get("destination"))
            if "destination" in entry
            else None
        )
        if "destination" in entry:
            parsed_destination = parse_destination_config(
                entry.get("destination"),
                context=f"repo '{repo_id}' destination",
            )
            if parsed_destination.valid:
                destination = normalize_manifest_destination(
                    parsed_destination.destination.to_dict()
                )
            else:
                for message in parsed_destination.errors:
                    issues.append(
                        ManifestValidationIssue(repo_id=repo_id, message=message)
                    )

        repos.append(
            ManifestRepo(
                id=repo_id.strip(),
                path=_relative_to_hub_root(hub_root, hub_root / path_val.strip()),
                enabled=bool(entry.get("enabled", True)),
                auto_run=bool(entry.get("auto_run", False)),
                kind=str(kind),
                worktree_of=(
                    str(entry.get("worktree_of")) if entry.get("worktree_of") else None
                ),
                branch=str(entry.get("branch")) if entry.get("branch") else None,
                display_name=(
                    str(entry.get("display_name"))
                    if entry.get("display_name")
                    else None
                ),
                worktree_setup_commands=(
                    [
                        str(cmd).strip()
                        for cmd in (entry.get("worktree_setup_commands") or [])
                        if isinstance(cmd, str) and str(cmd).strip()
                    ]
                    or None
                ),
                destination=destination,
            )
        )

    return repos, issues


def load_manifest_with_issues(
    manifest_path: Path, hub_root: Path
) -> tuple[Manifest, List[ManifestValidationIssue]]:
    if not manifest_path.exists():
        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        manifest = Manifest(version=MANIFEST_VERSION, repos=[], issues=[])
        save_manifest(manifest_path, manifest, hub_root)
        return manifest, []

    with manifest_path.open("r", encoding="utf-8") as f:
        raw_data = yaml.safe_load(f) or {}
    if not isinstance(raw_data, dict):
        raw_data = {}
    data = cast(Dict[str, Any], raw_data)

    removed_deprecated = _strip_deprecated_manifest_top_keys(data)

    version = data.get("version")
    if version not in {2, MANIFEST_VERSION}:
        raise ManifestError(
            f"Unsupported manifest version {version}; expected {MANIFEST_VERSION}"
        )
    repos, issues = _parse_manifest_repos_with_issues(
        repos_data=data.get("repos", []), hub_root=hub_root
    )
    manifest = Manifest(
        version=MANIFEST_VERSION,
        repos=repos,
        issues=list(issues),
    )
    if removed_deprecated:
        try:
            save_manifest(manifest_path, manifest, hub_root)
        except OSError as exc:
            _logger.warning(
                "Removed deprecated hub manifest keys %s but could not persist %s: %s",
                ", ".join(removed_deprecated),
                manifest_path,
                exc,
            )
        else:
            _logger.info(
                "Removed deprecated hub manifest keys from %s: %s",
                manifest_path,
                ", ".join(removed_deprecated),
            )
    return manifest, list(issues)


def load_manifest(manifest_path: Path, hub_root: Path) -> Manifest:
    manifest, _ = load_manifest_with_issues(manifest_path, hub_root)
    return manifest


def save_manifest(manifest_path: Path, manifest: Manifest, hub_root: Path) -> None:
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "version": MANIFEST_VERSION,
        "repos": [repo.to_dict(hub_root) for repo in manifest.repos],
    }
    with manifest_path.open("w", encoding="utf-8") as f:
        f.write(MANIFEST_HEADER)
        yaml.safe_dump(payload, f, sort_keys=False)
