"""Stable update facade and engine package."""

from __future__ import annotations

import shutil
import subprocess
import sys

from ._facade import (  # noqa: F401
    _REFRESH_OUTPUT_SUMMARY_MAX_CHARS,
    UpdateInProgressError,
    _acquire_update_lock,
    _available_update_target_definitions,
    _available_update_target_options,
    _backend_refresh_label,
    _capture_update_identity_hint,
    _chat_target_active,
    _chat_target_enableable,
    _default_update_target,
    _format_update_confirmation_warning,
    _get_update_target_definition,
    _is_systemd_backend,
    _is_systemd_service_active,
    _is_systemd_user_service_active,
    _is_valid_git_repo,
    _normalize_update_backend,
    _normalize_update_ref,
    _normalize_update_target,
    _read_update_lock,
    _read_update_status,
    _refresh_script,
    _refresh_script_committed_ok_status,
    _release_update_lock,
    _required_update_commands,
    _resolve_update_backend,
    _run_cmd,
    _run_refresh_script,
    _spawn_update_process,
    _summarize_refresh_output,
    _system_update_check,
    _system_update_worker,
    _systemd_scope_for_backend,
    _update_lock_active,
    _update_lock_path,
    _update_status_path,
    _update_target_restarts_surface,
    _write_update_status,
)
from .detect import (
    Backend,
    CgroupReader,
    LaunchctlReader,
    Scope,
    SupervisorIdentity,
    SystemctlReader,
    default_cgroup_reader,
    default_launchctl_reader,
    default_systemctl_reader,
    detect_container,
    detect_supervisor_identity,
    enrich_identity,
    guard_self_update,
    launchctl_has_restart_policy,
    parse_cgroup_identity,
    resolve_backend,
    systemctl_restart_policy,
    verify_cutover_routing,
)
from .engine import UpdateEngine, UpdateEngineConfig
from .launchd import (
    LaunchdPlistManager,
    LaunchdServiceResult,
    build_chat_plist_dict,
    discord_missing_env_names,
    discord_state,
    inject_opencode_path,
    normalize_chat_plist,
    normalize_hub_plist_text,
    normalize_process_limits,
    telegram_state,
)
from .source import (
    cache_refresh_failure_is_retryable as _update_cache_refresh_failure_is_retryable,
)
from .source import (
    cleanup_build_artifacts as _cleanup_update_build_artifacts,
)
from .source import (
    refresh_failure_is_retryable as _refresh_failure_is_retryable,
)
from .supervisors import (
    CommandAdapter,
    LaunchdAdapter,
    LaunchdManagedAdapter,
    LayeredSupervisor,
    RestartResult,
    SignalAdapter,
    SupervisorAdapter,
    SystemdAdapter,
    UpdateServices,
    build_layered_supervisor,
    resolve_systemctl_sudo_prefix,
)

__all__ = (
    "shutil",
    "subprocess",
    "sys",
    "Backend",
    "CgroupReader",
    "CommandAdapter",
    "LaunchctlReader",
    "LaunchdAdapter",
    "LaunchdManagedAdapter",
    "LaunchdPlistManager",
    "LaunchdServiceResult",
    "LayeredSupervisor",
    "RestartResult",
    "build_chat_plist_dict",
    "discord_missing_env_names",
    "discord_state",
    "inject_opencode_path",
    "normalize_chat_plist",
    "normalize_hub_plist_text",
    "normalize_process_limits",
    "telegram_state",
    "Scope",
    "SignalAdapter",
    "SupervisorAdapter",
    "SupervisorIdentity",
    "SystemctlReader",
    "SystemdAdapter",
    "UpdateEngine",
    "UpdateEngineConfig",
    "UpdateInProgressError",
    "UpdateServices",
    "_cleanup_update_build_artifacts",
    "_refresh_failure_is_retryable",
    "_update_cache_refresh_failure_is_retryable",
    "build_layered_supervisor",
    "default_cgroup_reader",
    "default_launchctl_reader",
    "default_systemctl_reader",
    "detect_container",
    "detect_supervisor_identity",
    "enrich_identity",
    "guard_self_update",
    "launchctl_has_restart_policy",
    "parse_cgroup_identity",
    "resolve_backend",
    "resolve_systemctl_sudo_prefix",
    "systemctl_restart_policy",
    "verify_cutover_routing",
)
