# ruff: noqa: F401

import pytest
from tests.discord_message_turns_support import (
    test_message_create_opencode_streaming_turn_surfaces_thinking_and_tool_updates,
    test_message_create_opencode_turn_does_not_duplicate_summary_with_metrics,
    test_message_create_opencode_turn_sends_summary_before_final,
    test_message_create_progress_edit_failures_are_best_effort_and_throttled,
    test_message_create_progress_failures_are_best_effort_and_do_not_block_completion,
    test_message_create_streaming_turn_accumulates_segmented_intermediate_outputs,
    test_message_create_streaming_turn_appends_final_metrics,
    test_message_create_streaming_turn_completion_sends_final_and_deletes_preview,
    test_message_create_streaming_turn_empty_final_includes_text_fallback_with_metrics,
    test_message_create_streaming_turn_enqueues_preview_delete_when_delete_fails,
    test_message_create_streaming_turn_exception_marks_progress_failed,
    test_message_create_streaming_turn_failure_before_completion_still_fails,
    test_message_create_streaming_turn_fallback_handles_cumulative_deltas,
    test_message_create_streaming_turn_fallback_preserves_multichunk_whitespace,
    test_message_create_streaming_turn_fallback_preserves_whitespace_only_chunks,
    test_message_create_streaming_turn_final_progress_omits_duplicate_terminal_output,
    test_message_create_streaming_turn_ignores_commentary_when_stream_falls_back,
    test_message_create_streaming_turn_ignores_late_failed_after_completed_output,
    test_message_create_streaming_turn_ignores_late_failed_with_stream_fallback,
    test_message_create_streaming_turn_ignores_user_message_delta,
    test_message_create_streaming_turn_keeps_components_cleared_after_completion,
    test_message_create_streaming_turn_multi_chunk_deletes_preview_and_sends_chunks,
    test_message_create_streaming_turn_persists_full_output_in_progress,
    test_message_create_streaming_turn_posts_progress_placeholder_and_edits,
    test_message_create_streaming_turn_recovers_if_wait_disconnects_after_completion,
    test_message_create_streaming_turn_recovers_if_wait_times_out_after_streamed_completion,
    test_message_create_streaming_turn_skips_live_progress_when_parallel_streaming_is_disabled,
    test_message_create_streaming_turn_surfaces_fast_transient_thinking_and_tool_updates,
    test_message_create_streaming_turn_updates_token_usage_log_line_in_place,
    test_message_create_streaming_turn_uses_assistant_stream_when_final_empty,
    test_message_create_turn_sends_only_final_attachment_when_long,
    test_message_create_turn_uses_progress_snapshot_when_final_empty,
)

pytestmark = pytest.mark.slow
