from __future__ import annotations

import json
import sqlite3
from pathlib import Path

import pytest

from codex_autorunner.bootstrap import seed_hub_files
from codex_autorunner.core.config import CONFIG_FILENAME, DEFAULT_HUB_CONFIG
from codex_autorunner.core.pma_chat_delivery import (
    deliver_pma_notification,
    notify_preferred_bound_chat_for_workspace,
    notify_primary_pma_chat_for_repo,
)
from codex_autorunner.core.pma_notification_store import (
    PmaNotificationStore,
    build_notification_context_block,
)
from codex_autorunner.integrations.discord.state import DiscordStateStore
from codex_autorunner.integrations.telegram.state import TelegramStateStore, topic_key
from tests.conftest import write_test_config


def _hub(tmp_path: Path) -> Path:
    hub_root = tmp_path / "hub"
    seed_hub_files(hub_root, force=True)
    cfg = json.loads(json.dumps(DEFAULT_HUB_CONFIG))
    cfg["discord_bot"]["enabled"] = True
    cfg["telegram_bot"]["enabled"] = True
    write_test_config(hub_root / CONFIG_FILENAME, cfg)
    return hub_root


def _write_manifest(hub_root: Path, repo_id: str, workspace: Path) -> None:
    manifest_path = hub_root / ".codex-autorunner" / "manifest.yml"
    rel_path = workspace.relative_to(hub_root).as_posix()
    manifest_path.write_text(
        "\n".join(
            [
                "# GENERATED by CAR - DO NOT EDIT",
                "version: 3",
                "repos:",
                f"  - id: {repo_id}",
                f"    path: {rel_path}",
                "    enabled: true",
                "    auto_run: false",
                "    kind: base",
                "",
            ]
        ),
        encoding="utf-8",
    )


def _set_discord_binding_updated_at(
    state_path: Path, channel_id: str, updated_at: str
) -> None:
    conn = sqlite3.connect(state_path)
    try:
        conn.execute(
            "UPDATE channel_bindings SET updated_at = ? WHERE channel_id = ?",
            (updated_at, channel_id),
        )
        conn.commit()
    finally:
        conn.close()


def _set_telegram_topic_updated_at(state_path: Path, key: str, updated_at: str) -> None:
    conn = sqlite3.connect(state_path)
    try:
        conn.execute(
            "UPDATE telegram_topics SET updated_at = ?, last_active_at = ? WHERE topic_key = ?",
            (updated_at, updated_at, key),
        )
        conn.commit()
    finally:
        conn.close()


@pytest.mark.anyio
async def test_notify_primary_pma_chat_prefers_freshest_matching_discord_binding(
    tmp_path: Path,
) -> None:
    hub_root = _hub(tmp_path)
    workspace = (hub_root / "worktrees" / "repo-a").resolve()
    workspace.mkdir(parents=True, exist_ok=True)
    _write_manifest(hub_root, "repo-a", workspace)

    discord_store = DiscordStateStore(
        hub_root / ".codex-autorunner" / "discord_state.sqlite3"
    )
    telegram_store = TelegramStateStore(
        hub_root / ".codex-autorunner" / "telegram_state.sqlite3"
    )
    try:
        await discord_store.upsert_binding(
            channel_id="older-discord",
            guild_id="guild-1",
            workspace_path=str(workspace),
            repo_id="repo-a",
        )
        await discord_store.update_pma_state(
            channel_id="older-discord",
            pma_enabled=True,
            pma_prev_workspace_path=str(workspace),
            pma_prev_repo_id="repo-a",
        )
        _set_discord_binding_updated_at(
            hub_root / ".codex-autorunner" / "discord_state.sqlite3",
            "older-discord",
            "2026-03-18T08:22:01Z",
        )

        await discord_store.upsert_binding(
            channel_id="newer-discord",
            guild_id="guild-1",
            workspace_path=str(workspace),
            repo_id="repo-a",
        )
        await discord_store.update_pma_state(
            channel_id="newer-discord",
            pma_enabled=True,
            pma_prev_workspace_path=str(workspace),
            pma_prev_repo_id="repo-a",
        )
        _set_discord_binding_updated_at(
            hub_root / ".codex-autorunner" / "discord_state.sqlite3",
            "newer-discord",
            "2026-03-18T08:22:09Z",
        )

        await telegram_store.bind_topic(
            topic_key(1001, 2002),
            str(workspace),
            repo_id="repo-a",
        )
        telegram_state = await telegram_store.load()
        telegram_topic = telegram_state.topics[topic_key(1001, 2002)]
        telegram_topic.pma_enabled = True
        telegram_topic.pma_prev_repo_id = "repo-a"
        await telegram_store.save(telegram_state)
        _set_telegram_topic_updated_at(
            hub_root / ".codex-autorunner" / "telegram_state.sqlite3",
            topic_key(1001, 2002),
            "2026-03-18T08:22:05Z",
        )

        outcome = await notify_primary_pma_chat_for_repo(
            hub_root=hub_root,
            repo_id="repo-a",
            message="Escalation message",
            correlation_id="corr-1",
        )

        assert outcome["targets"] == 1
        assert outcome["published"] == 1

        await discord_store.close()
        await telegram_store.close()
        discord_store = DiscordStateStore(
            hub_root / ".codex-autorunner" / "discord_state.sqlite3"
        )
        telegram_store = TelegramStateStore(
            hub_root / ".codex-autorunner" / "telegram_state.sqlite3"
        )
        discord_outbox = await discord_store.list_outbox()
        telegram_outbox = await telegram_store.list_outbox()
        assert any(
            record.channel_id == "newer-discord"
            and record.payload_json.get("content") == "Escalation message"
            for record in discord_outbox
        )
        assert not telegram_outbox
    finally:
        await discord_store.close()
        await telegram_store.close()


@pytest.mark.anyio
async def test_deliver_pma_notification_persists_replyable_context_for_bound_delivery(
    tmp_path: Path,
) -> None:
    hub_root = _hub(tmp_path)
    workspace = (hub_root / "worktrees" / "repo-f").resolve()
    workspace.mkdir(parents=True, exist_ok=True)
    _write_manifest(hub_root, "repo-f", workspace)

    discord_store = DiscordStateStore(
        hub_root / ".codex-autorunner" / "discord_state.sqlite3"
    )
    try:
        await discord_store.upsert_binding(
            channel_id="repo-f-discord",
            guild_id="guild-1",
            workspace_path=str(workspace),
            repo_id="repo-f",
        )
        _set_discord_binding_updated_at(
            hub_root / ".codex-autorunner" / "discord_state.sqlite3",
            "repo-f-discord",
            "2026-03-18T11:00:01Z",
        )

        outcome = await deliver_pma_notification(
            hub_root=hub_root,
            workspace_root=workspace,
            repo_id="repo-f",
            message="Dispatch needs review",
            correlation_id="corr-6",
            delivery="auto",
            source_kind="dispatch_paused",
            run_id="run-123",
            managed_thread_id="thread-123",
            context_payload={"wake_up": {"kind": "dispatch_paused"}},
        )

        assert outcome == {"route": "bound", "targets": 1, "published": 1}

        outbox = await discord_store.list_outbox()
        assert len(outbox) == 1
        record = outbox[0]
        assert record.channel_id == "repo-f-discord"
        assert record.payload_json.get("content") == "Dispatch needs review"

        notification_store = PmaNotificationStore(hub_root)
        delivered = notification_store.mark_delivered(
            delivery_record_id=record.record_id,
            delivered_message_id="discord-msg-123",
        )
        assert delivered is not None
        assert delivered.delivery_mode == "bound"
        assert delivered.repo_id == "repo-f"
        assert delivered.workspace_root == str(workspace)
        assert delivered.run_id == "run-123"
        assert delivered.managed_thread_id == "thread-123"
        assert delivered.context == {
            "message": "Dispatch needs review",
            "correlation_id": "corr-6",
            "source_kind": "dispatch_paused",
            "wake_up": {"kind": "dispatch_paused"},
        }

        reply_target = notification_store.get_reply_target(
            surface_kind="discord",
            surface_key="repo-f-discord",
            delivered_message_id="discord-msg-123",
        )
        assert reply_target == delivered
        context_block = build_notification_context_block(reply_target)
        assert "<notification_context>" in context_block
        assert '"notification_id"' in context_block
        assert '"dispatch_paused"' in context_block
    finally:
        await discord_store.close()


@pytest.mark.anyio
async def test_notify_preferred_bound_chat_for_workspace_uses_non_pma_preferred_surface(
    tmp_path: Path,
) -> None:
    hub_root = _hub(tmp_path)
    workspace = (hub_root / "worktrees" / "repo-b").resolve()
    workspace.mkdir(parents=True, exist_ok=True)
    _write_manifest(hub_root, "repo-b", workspace)

    discord_store = DiscordStateStore(
        hub_root / ".codex-autorunner" / "discord_state.sqlite3"
    )
    telegram_store = TelegramStateStore(
        hub_root / ".codex-autorunner" / "telegram_state.sqlite3"
    )
    try:
        await discord_store.upsert_binding(
            channel_id="repo-discord",
            guild_id="guild-1",
            workspace_path=str(workspace),
            repo_id="repo-b",
        )
        _set_discord_binding_updated_at(
            hub_root / ".codex-autorunner" / "discord_state.sqlite3",
            "repo-discord",
            "2026-03-18T09:00:10Z",
        )
        await telegram_store.bind_topic(
            topic_key(2001, 3002),
            str(workspace),
            repo_id="repo-b",
        )
        _set_telegram_topic_updated_at(
            hub_root / ".codex-autorunner" / "telegram_state.sqlite3",
            topic_key(2001, 3002),
            "2026-03-18T09:00:01Z",
        )

        outcome = await notify_preferred_bound_chat_for_workspace(
            hub_root=hub_root,
            workspace_root=workspace,
            repo_id="repo-b",
            message="Auto reply mirror",
            correlation_id="corr-2",
        )

        assert outcome["targets"] == 1
        assert outcome["published"] == 1

        await discord_store.close()
        await telegram_store.close()
        discord_store = DiscordStateStore(
            hub_root / ".codex-autorunner" / "discord_state.sqlite3"
        )
        telegram_store = TelegramStateStore(
            hub_root / ".codex-autorunner" / "telegram_state.sqlite3"
        )
        discord_outbox = await discord_store.list_outbox()
        telegram_outbox = await telegram_store.list_outbox()
        assert any(
            record.channel_id == "repo-discord"
            and record.payload_json.get("content") == "Auto reply mirror"
            for record in discord_outbox
        )
        assert not telegram_outbox
    finally:
        await discord_store.close()
        await telegram_store.close()


@pytest.mark.anyio
async def test_notify_primary_pma_chat_matches_workspace_only_binding(
    tmp_path: Path,
) -> None:
    hub_root = _hub(tmp_path)
    workspace = (hub_root / "worktrees" / "repo-c").resolve()
    workspace.mkdir(parents=True, exist_ok=True)
    _write_manifest(hub_root, "repo-c", workspace)

    discord_store = DiscordStateStore(
        hub_root / ".codex-autorunner" / "discord_state.sqlite3"
    )
    try:
        await discord_store.upsert_binding(
            channel_id="workspace-only-pma",
            guild_id="guild-1",
            workspace_path=str(hub_root),
            repo_id=None,
        )
        await discord_store.update_pma_state(
            channel_id="workspace-only-pma",
            pma_enabled=True,
            pma_prev_workspace_path=str(workspace),
            pma_prev_repo_id=None,
        )

        outcome = await notify_primary_pma_chat_for_repo(
            hub_root=hub_root,
            repo_id="repo-c",
            message="Workspace matched escalation",
            correlation_id="corr-3",
        )

        assert outcome["targets"] == 1
        assert outcome["published"] == 1
        outbox = await discord_store.list_outbox()
        assert any(
            record.channel_id == "workspace-only-pma"
            and record.payload_json.get("content") == "Workspace matched escalation"
            for record in outbox
        )
    finally:
        await discord_store.close()


@pytest.mark.anyio
async def test_notify_preferred_bound_chat_skips_stale_telegram_scope(
    tmp_path: Path,
) -> None:
    hub_root = _hub(tmp_path)
    workspace = (hub_root / "worktrees" / "repo-d").resolve()
    workspace.mkdir(parents=True, exist_ok=True)
    _write_manifest(hub_root, "repo-d", workspace)

    telegram_store = TelegramStateStore(
        hub_root / ".codex-autorunner" / "telegram_state.sqlite3"
    )
    try:
        stale_key = topic_key(3001, 4002, scope="repo-d-old")
        await telegram_store.bind_topic(stale_key, str(workspace), repo_id="repo-d")
        state = await telegram_store.load()
        state.topic_scopes[topic_key(3001, 4002)] = "repo-d-current"
        await telegram_store.save(state)

        outcome = await notify_preferred_bound_chat_for_workspace(
            hub_root=hub_root,
            workspace_root=workspace,
            repo_id="repo-d",
            message="Should not go to stale scope",
            correlation_id="corr-4",
        )

        assert outcome["targets"] == 0
        assert outcome["published"] == 0
        assert not await telegram_store.list_outbox()
    finally:
        await telegram_store.close()


@pytest.mark.anyio
async def test_notify_preferred_bound_chat_falls_back_when_preferred_surface_mismatches_repo(
    tmp_path: Path,
) -> None:
    hub_root = _hub(tmp_path)
    workspace = (hub_root / "worktrees" / "repo-e").resolve()
    workspace.mkdir(parents=True, exist_ok=True)
    _write_manifest(hub_root, "repo-e", workspace)

    discord_store = DiscordStateStore(
        hub_root / ".codex-autorunner" / "discord_state.sqlite3"
    )
    telegram_store = TelegramStateStore(
        hub_root / ".codex-autorunner" / "telegram_state.sqlite3"
    )
    try:
        await discord_store.upsert_binding(
            channel_id="repo-e-discord",
            guild_id="guild-1",
            workspace_path=str(workspace),
            repo_id="repo-e",
        )
        _set_discord_binding_updated_at(
            hub_root / ".codex-autorunner" / "discord_state.sqlite3",
            "repo-e-discord",
            "2026-03-18T10:00:01Z",
        )

        await telegram_store.bind_topic(
            topic_key(5001, 6002),
            str(workspace),
            repo_id="other-repo",
        )
        _set_telegram_topic_updated_at(
            hub_root / ".codex-autorunner" / "telegram_state.sqlite3",
            topic_key(5001, 6002),
            "2026-03-18T10:00:10Z",
        )

        outcome = await notify_preferred_bound_chat_for_workspace(
            hub_root=hub_root,
            workspace_root=workspace,
            repo_id="repo-e",
            message="Fallback to discord",
            correlation_id="corr-5",
        )

        assert outcome["targets"] == 1
        assert outcome["published"] == 1
        outbox = await discord_store.list_outbox()
        assert any(
            record.channel_id == "repo-e-discord"
            and record.payload_json.get("content") == "Fallback to discord"
            for record in outbox
        )
    finally:
        await discord_store.close()
        await telegram_store.close()
