"""Compatibility facade for config layering helpers.

Default config data, YAML merge/load helpers, and source layering live in
focused owner modules.  This module remains as the legacy import surface for
contract tests and older internal callers while new code imports narrow owners.
"""

from .config_defaults import (
    DEFAULT_HUB_CONFIG,
    DEFAULT_REPO_CONFIG,
    DEFAULT_REPO_DEFAULTS,
    PMA_DEFAULT_MAX_TEXT_CHARS,
    PMA_DEFAULT_TURN_IDLE_TIMEOUT_SECONDS,
    REPO_DEFAULT_KEYS,
    REPO_SHARED_KEYS,
    TWELVE_HOUR_SECONDS,
    _default_agents_section,
    _default_app_server_section,
    _default_apps_section,
    _default_discord_bot_section,
    _default_github_automation_section,
    _default_housekeeping_section,
    _default_opencode_section,
    _default_server_section,
    _default_static_assets_section,
    _default_telegram_bot_section,
    _default_templates_section,
    _default_terminal_section,
    _default_update_linux_service_names,
    _default_update_section,
    _default_usage_section,
)
from .config_generated import (
    GENERATED_CONFIG_HEADER,
    GENERATED_HUB_CONFIG_PRESERVE_KEYS,
    PMA_LEGACY_GENERATED_MAX_TEXT_CHARS,
)
from .config_sources import (
    CONFIG_FILENAME,
    REPO_OVERRIDE_FILENAME,
    ROOT_CONFIG_FILENAME,
    ROOT_OVERRIDE_FILENAME,
    derive_repo_config_data,
    find_nearest_hub_config_path,
    load_root_defaults,
    repo_shared_overrides_from_hub,
    resolve_hub_config_data,
    update_override_templates,
)
from .config_yaml import (
    _clone_config_value,
    _load_yaml_dict,
    _mapping_has_nested_key,
    _merge_defaults,
)

__all__ = [
    "CONFIG_FILENAME",
    "DEFAULT_HUB_CONFIG",
    "DEFAULT_REPO_CONFIG",
    "DEFAULT_REPO_DEFAULTS",
    "GENERATED_CONFIG_HEADER",
    "GENERATED_HUB_CONFIG_PRESERVE_KEYS",
    "PMA_DEFAULT_MAX_TEXT_CHARS",
    "PMA_DEFAULT_TURN_IDLE_TIMEOUT_SECONDS",
    "PMA_LEGACY_GENERATED_MAX_TEXT_CHARS",
    "REPO_DEFAULT_KEYS",
    "REPO_OVERRIDE_FILENAME",
    "REPO_SHARED_KEYS",
    "ROOT_CONFIG_FILENAME",
    "ROOT_OVERRIDE_FILENAME",
    "TWELVE_HOUR_SECONDS",
    "_clone_config_value",
    "_default_agents_section",
    "_default_app_server_section",
    "_default_apps_section",
    "_default_discord_bot_section",
    "_default_github_automation_section",
    "_default_housekeeping_section",
    "_default_opencode_section",
    "_default_server_section",
    "_default_static_assets_section",
    "_default_telegram_bot_section",
    "_default_templates_section",
    "_default_terminal_section",
    "_default_update_linux_service_names",
    "_default_update_section",
    "_default_usage_section",
    "_load_yaml_dict",
    "_mapping_has_nested_key",
    "_merge_defaults",
    "derive_repo_config_data",
    "find_nearest_hub_config_path",
    "load_root_defaults",
    "repo_shared_overrides_from_hub",
    "resolve_hub_config_data",
    "update_override_templates",
]
