"""Compatibility facade for managed-thread identity helpers.

The canonical authority now lives in ``core.managed_thread_identity`` backed by
``orchestration.sqlite3``. ``app_server_threads.json`` remains only as a
transitional compatibility cache/export.
"""

from ...core.managed_thread_identity import (
    APP_SERVER_THREADS_CORRUPT_SUFFIX,
    APP_SERVER_THREADS_FILENAME,
    APP_SERVER_THREADS_NOTICE_SUFFIX,
    APP_SERVER_THREADS_VERSION,
    FEATURE_KEYS,
    FILE_CHAT_HERMES_KEY,
    FILE_CHAT_HERMES_PREFIX,
    FILE_CHAT_KEY,
    FILE_CHAT_OPENCODE_KEY,
    FILE_CHAT_OPENCODE_PREFIX,
    FILE_CHAT_PREFIX,
    PMA_HERMES_KEY,
    PMA_HERMES_PREFIX,
    PMA_KEY,
    PMA_OPENCODE_KEY,
    PMA_OPENCODE_PREFIX,
    PMA_PREFIX,
    AppServerThreadRegistry,
    ManagedThreadIdentityStore,
    default_app_server_threads_path,
    file_chat_discord_key,
    file_chat_target_key,
    normalize_feature_key,
    pma_automation_key,
    pma_base_key,
    pma_legacy_alias_key,
    pma_legacy_alias_keys,
    pma_legacy_migration_fallback_keys,
    pma_prefix_for_agent,
    pma_prefixes_for_reset,
    pma_topic_scoped_key,
)

__all__ = [
    "APP_SERVER_THREADS_CORRUPT_SUFFIX",
    "APP_SERVER_THREADS_FILENAME",
    "APP_SERVER_THREADS_NOTICE_SUFFIX",
    "APP_SERVER_THREADS_VERSION",
    "AppServerThreadRegistry",
    "FEATURE_KEYS",
    "FILE_CHAT_HERMES_KEY",
    "FILE_CHAT_HERMES_PREFIX",
    "FILE_CHAT_KEY",
    "FILE_CHAT_OPENCODE_KEY",
    "FILE_CHAT_OPENCODE_PREFIX",
    "FILE_CHAT_PREFIX",
    "ManagedThreadIdentityStore",
    "PMA_HERMES_KEY",
    "PMA_HERMES_PREFIX",
    "PMA_KEY",
    "PMA_OPENCODE_KEY",
    "PMA_OPENCODE_PREFIX",
    "PMA_PREFIX",
    "default_app_server_threads_path",
    "file_chat_discord_key",
    "file_chat_target_key",
    "normalize_feature_key",
    "pma_automation_key",
    "pma_base_key",
    "pma_legacy_alias_key",
    "pma_legacy_alias_keys",
    "pma_legacy_migration_fallback_keys",
    "pma_prefix_for_agent",
    "pma_prefixes_for_reset",
    "pma_topic_scoped_key",
]
