from __future__ import annotations

PMA_AUTOMATION_VERSION = 1
DEFAULT_PMA_LANE_ID = "pma:default"
DEFAULT_WATCHDOG_IDLE_SECONDS = 300

TIMER_TYPE_ONE_SHOT = "one_shot"
TIMER_TYPE_WATCHDOG = "watchdog"

SUBSCRIPTION_STATE_ACTIVE = "active"
SUBSCRIPTION_STATE_CANCELLED = "cancelled"

WAKEUP_STATE_PENDING = "pending"
WAKEUP_STATE_DISPATCHED = "dispatched"

TIMER_STATE_PENDING = "pending"
TIMER_STATE_FIRED = "fired"
TIMER_STATE_CANCELLED = "cancelled"

DELIVERY_MODE_AUTO = "auto"
DELIVERY_MODE_NONE = "none"
DELIVERY_MODE_BOUND = "bound"
DELIVERY_MODE_PRIMARY_PMA = "primary_pma"
DELIVERY_MODE_SUPPRESSED = "suppressed_duplicate"

ROUTE_EXPLICIT = "explicit"
ROUTE_PRIMARY_PMA = "primary_pma"
ROUTE_BOUND = "bound"

SURFACE_KIND_DISCORD = "discord"
SURFACE_KIND_TELEGRAM = "telegram"
VALID_SURFACE_KINDS = frozenset({SURFACE_KIND_DISCORD, SURFACE_KIND_TELEGRAM})

SOURCE_KIND_MANAGED_THREAD_COMPLETED = "managed_thread_completed"

NOTICE_KIND_TERMINAL_FOLLOWUP = "terminal_followup"
NOTICE_KIND_NOOP = "noop"
NOTICE_KIND_ESCALATION = "escalation"
NOTICE_KIND_PROGRESS = "progress"

SUPPRESSED_REASON_DUPLICATE_NOOP = "duplicate_noop"
