"""Platform-agnostic chat adapter contracts (adapter layer)."""

from .adapter import ChatAdapter, SendAttachmentRequest, SendTextRequest
from .callbacks import (
    CALLBACK_AGENT,
    CALLBACK_APPROVAL,
    CALLBACK_BIND,
    CALLBACK_CANCEL,
    CALLBACK_COMPACT,
    CALLBACK_EFFORT,
    CALLBACK_FLOW,
    CALLBACK_FLOW_RUN,
    CALLBACK_MODEL,
    CALLBACK_PAGE,
    CALLBACK_QUESTION_CANCEL,
    CALLBACK_QUESTION_CUSTOM,
    CALLBACK_QUESTION_DONE,
    CALLBACK_QUESTION_OPTION,
    CALLBACK_RESUME,
    CALLBACK_REVIEW_COMMIT,
    CALLBACK_UPDATE,
    CALLBACK_UPDATE_CONFIRM,
    CallbackCodec,
    LogicalCallback,
    decode_logical_callback,
    encode_logical_callback,
)
from .capabilities import ChatCapabilities
from .dispatcher import (
    ChatDispatcher,
    DispatchContext,
    DispatchResult,
    build_dispatch_context,
    conversation_id_for,
    is_bypass_event,
)
from .errors import (
    ChatAdapterError,
    ChatAdapterPermanentError,
    ChatAdapterTimeoutError,
    ChatAdapterTransientError,
)
from .models import (
    ChatAction,
    ChatAttachment,
    ChatEvent,
    ChatInteractionEvent,
    ChatInteractionRef,
    ChatMessageEvent,
    ChatMessageRef,
    ChatThreadRef,
)
from .renderer import RenderedText, TextRenderer
from .service import ChatBotServiceCore, ChatStateStore
from .transport import ChatTransport

__all__ = [
    "ChatAction",
    "ChatAdapter",
    "ChatAdapterError",
    "ChatAdapterPermanentError",
    "ChatAdapterTimeoutError",
    "ChatAdapterTransientError",
    "ChatAttachment",
    "ChatCapabilities",
    "ChatBotServiceCore",
    "CallbackCodec",
    "ChatDispatcher",
    "ChatEvent",
    "ChatInteractionEvent",
    "ChatInteractionRef",
    "ChatMessageEvent",
    "ChatMessageRef",
    "ChatStateStore",
    "ChatThreadRef",
    "ChatTransport",
    "DispatchContext",
    "DispatchResult",
    "LogicalCallback",
    "RenderedText",
    "CALLBACK_AGENT",
    "CALLBACK_APPROVAL",
    "CALLBACK_BIND",
    "CALLBACK_CANCEL",
    "CALLBACK_COMPACT",
    "CALLBACK_EFFORT",
    "CALLBACK_FLOW",
    "CALLBACK_FLOW_RUN",
    "CALLBACK_MODEL",
    "CALLBACK_PAGE",
    "CALLBACK_QUESTION_CANCEL",
    "CALLBACK_QUESTION_CUSTOM",
    "CALLBACK_QUESTION_DONE",
    "CALLBACK_QUESTION_OPTION",
    "CALLBACK_RESUME",
    "CALLBACK_REVIEW_COMMIT",
    "CALLBACK_UPDATE",
    "CALLBACK_UPDATE_CONFIRM",
    "SendAttachmentRequest",
    "SendTextRequest",
    "TextRenderer",
    "build_dispatch_context",
    "conversation_id_for",
    "decode_logical_callback",
    "encode_logical_callback",
    "is_bypass_event",
]
